version: "3.9"
services:
  artcatalog:
    build: .
    container_name: artcatalog-simple
    ports:
      - "9000:8000"
    environment:
      - APP_ENV=production
      - TZ=Europe/Prague
    volumes:
      - /opt/artworkDB/data:/app/data
      - /opt/artworkDB/app/media:/app/app/media
    restart: unless-stopped
